### ISSUE TITLE
fix: `mongodb` - password with special character '@' must be escaped

### ISSUE THREAD

**Issue by christophedumont5** [freelabz/secator#176]
J'ai configurer l'authentification sur la base mongodb. 

J'ai alors modifié le fichier .env comme suit 

MONGODB_URL=mongodb://admin:1234567@localhost:27017

Quand je lance une task il y a une erreur : InvalidURI: Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus.

**Comment by ocervell** [comment]
Tu dois avoir un `@` dans ton mot de passe j'imagine ?

Si on utilise `urllib.parse.quote_plus` il va falloir diviser les variables d'environnement pour l'authent avec `MONGODB_HOST`, `MONGODB_USERNAME`, `MONGODB_PASSWORD` j'avais espéré ne pas avoir à faire ça vu que ça rend l'utilisation moins user friendly.

**Comment by ocervell** [comment]
Je pense qu'on va implémenter là première solution, c'est le moins contraignant pour l'utilisateur

**Comment by ocervell** [comment]
@christophedumont5 peux-tu tester la PR ci-dessus sur ton environnement et me dire si ton problème est résolu ?

**Comment by christophedumont5** [comment]
Yes, ca fonctionne !
