### ISSUE TITLE
feat: search targets in all reports

### ISSUE THREAD

**Issue by hugo-syn** [freelabz/secator#315]
**Describe the bug**
It's a feature request, I would like to be able to input an url/domain and know what task/workflows have already been performed and if there is a report indicate the file path to use the `report show` command.

I really love your tool thank you :)

**Comment by ocervell** [comment]
This is an interesting potential feature;

There is a `report list` command planned already, which will allow to list all reports, maybe matching some filters. I think that's what you want ;)
