### ISSUE TITLE
return code 1 with gitleaks

### ISSUE THREAD

**Issue by 0xlildoudou** [freelabz/secator#440]
**Describe the bug**
Hello,
I'm trying to implement gitleaks in secator but I have a problem. When running gitleaks, if it finds any secrets, it returns a “1” return code, which shuts down secator.
Do you know if I can skip the return code in secator?

**Comment by 0xlildoudou** [comment]
i have read the --help of gitleaks and i have find the options

**Comment by ocervell** [comment]
Hi there,

I saw your fixed your issue, but I thought adding some suggestions could help others:

- You can ignore non-standard return codes by setting `ignore_return_code = True` in your task class (see [fping implementation](https://github.com/freelabz/secator/blob/main/secator%2Ftasks%2Ffping.py) for an example)

- [Integrating an external command (docs)](https://docs.freelabz.com/for-developers/writing-tasks/integrating-an-external-command): an in-depth guide for new command integrations that has been completely rewritten recently and should help you write your integration faster.
